from django.core.management.base import BaseCommand
from boarder.models import Boarder


class Command(BaseCommand):
    help = "Loads data into boarder table"

    def handle(self, *args, **options):
        boarders = [
            {
                "last_name": "BAUTISTA",
                "first_name": "CAMILLE",
                "middle_name": "TAGBAGO",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "MORALES",
                "degree_program": "BSIT",
                "year_level": "FIRST",
                "email": "camillebautista208@gmail.com",
                "phone_number": "09263835531",
                "room_number": "2FR2",
                "move_in_date": "2025-10-24",
            },
            {
                "last_name": "CANO",
                "first_name": "JESSA MARIE",
                "middle_name": "DE LA CRUZ",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "BUYABOD",
                "degree_program": "BSBA",
                "year_level": "FIRST",
                "email": "jessacano0@gmail.com",
                "phone_number": "09150182046",
                "room_number": "2FR3",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "FERANGCO",
                "first_name": "LEIZEL",
                "middle_name": "PAALAM",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "BUENAVISTA",
                "barangay": "LIPATA",
                "degree_program": "SHS",
                "year_level": "SECOND",
                "email": "ferangcolizz@gmail.com",
                "phone_number": "09318798823",
                "room_number": "3FR1",
                "move_in_date": "2025-06-16",
            },
            {
                "last_name": "MAGANA",
                "first_name": "MIKYLA CARISSE",
                "middle_name": "ASIS",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "KILO-KILO",
                "degree_program": "BSI/T",
                "year_level": "THIRD",
                "email": "magana.mikylacarisse@marsu.edu.ph",
                "phone_number": "09260228244",
                "room_number": "2FR2",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "MENDREJE",
                "first_name": "JHANA MAE",
                "middle_name": "LASLAS",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "MASAGUISI",
                "degree_program": "BSCE",
                "year_level": "SECOND",
                "email": "mendreje.jhanamae@marsu.edu.ph",
                "phone_number": "09457869532",
                "room_number": "2FR2",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "PAEZ",
                "first_name": "JENNIE",
                "middle_name": "REVILLOZA",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "KILO-KILO",
                "degree_program": "BSEE",
                "year_level": "SECOND",
                "email": "jenniepaez239@gmail.com",
                "phone_number": "09776219502",
                "room_number": "2FR2",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "PASTORAL",
                "first_name": "JANINE",
                "middle_name": "MURILLO",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "MASAGUISI",
                "degree_program": "BSEE",
                "year_level": "SECOND",
                "email": "pastoral.janine@marsu.edu.ph",
                "phone_number": "09460757803",
                "room_number": "2FR1",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "PERNIA",
                "first_name": "MARIEL",
                "middle_name": "RAMENTO",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "PANTAYIN",
                "degree_program": "BSBA",
                "year_level": "FIRST",
                "email": "marielpernia70@gmail.com",
                "phone_number": "09109492694",
                "room_number": "2FR3",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "RICAFORT",
                "first_name": "ALLEAH",
                "middle_name": "ROVEDILLO",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "ALOBO",
                "degree_program": "BSM",
                "year_level": "SECOND",
                "email": "ricafortalleah@gmail.com",
                "phone_number": "09634160555",
                "room_number": "3FR1",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "RICAMATA",
                "first_name": "ALYSA",
                "middle_name": "REGALADO",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "BUYABOD",
                "degree_program": "BSBA",
                "year_level": "FIRST",
                "email": "alysaricamata@gmail.com",
                "phone_number": "09076599155",
                "room_number": "2FR3",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "SANTUYO",
                "first_name": "KASHIECA CLAUI",
                "middle_name": "REANZARES",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "BUENAVISTA",
                "barangay": "YOOK",
                "degree_program": "BSI/T",
                "year_level": "FIRST",
                "email": "santuyokashieca9@gmail.com",
                "phone_number": "09704793733",
                "room_number": "3FR1",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "TUAZON",
                "first_name": "KRISTINE JOY",
                "middle_name": "GALUPO",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "GASAN",
                "barangay": "BANUYO",
                "degree_program": "BSI/T",
                "year_level": "FIRST",
                "email": "tuazon.kristinejoy@marsu.edu.ph",
                "phone_number": "09647689452",
                "room_number": "2FR3",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "VALENCIA",
                "first_name": "CZAINIE",
                "middle_name": "MURILLO",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "BUENAVISTA",
                "barangay": "LIPATA",
                "degree_program": "SHS",
                "year_level": "SECOND",
                "email": "czaiivalencia@gmail.com",
                "phone_number": "09310188086",
                "room_number": "3FR1",
                "move_in_date": "2025-07-28",
            },
            {
                "last_name": "VIZARRA",
                "first_name": "VENICE ELAINE",
                "middle_name": "RICAMATA",
                "sex": "F",
                "province": "MARINDUQUE",
                "municipality": "SANTA CRUZ",
                "barangay": "MATALABA",
                "degree_program": "BSM",
                "year_level": "SECOND",
                "email": "veniceelainev@gmail.com",
                "phone_number": "09462475124",
                "room_number": "2FR1",
                "move_in_date": "2025-07-28",
            }
        ]

        for boarder in boarders:
            Boarder.objects.create(**boarder)

        self.stdout.write(self.style.SUCCESS("Data loaded successfully!"))
