# Generated by Django 5.2.7 on 2026-01-12 08:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0010_alter_boarder_profile_photo_alter_boarder_role'),
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='boarder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otps', to='boarder.boarder'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='OTP must be 6 digits', regex='^\\d{6}$')]),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['boarder', 'channel', 'created_at'], name='otp_otp_boarder_dedefb_idx'),
        ),
    ]
