# Generated by Django 5.2.7 on 2025-10-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
