# Generated by Django 5.2.7 on 2025-10-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_alter_module_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='slug',
            new_name='redirect_url',
        ),
    ]
