# Generated by Django 5.2.1 on 2025-10-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boarder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], max_length=1)),
                ('province', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('degree_program', models.CharField(max_length=100)),
                ('year_level', models.CharField(choices=[('FIRST', '1st Year'), ('SECOND', '2nd Year'), ('THIRD', '3rd Year'), ('FOURTH', '4th Year')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('room_number', models.CharField(max_length=10)),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
