# Generated by Django 5.2.7 on 2025-10-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
