# Generated by Django 5.2.7 on 2025-10-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
