# Generated by Django 5.2.7 on 2025-10-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0002_alter_boarder_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='degree_program',
            field=models.CharField(choices=[('SHS', 'Senior High School'), ('BAC', 'Bachelor of Arts in Communication'), ('BAELS', 'Bachelor of Arts in English Language Studies'), ('BCAEd', 'Bachelor of Culture and Arts Education'), ('BEEd', 'Bachelor of Elementary Education'), ('BSEntrep', 'Bachelor of in Science in Entrepreneurship'), ('BPA', 'Bachelor of Public Administration'), ('BSA', 'Bachelor of Science in Accountancy'), ('BSBA', 'Bachelor of Science in Business Administration'), ('BSCE', 'Bachelor of Science in Civil Engineering'), ('BSCpE', 'Bachelor of Science in Computer Engineering'), ('BSCrim', 'Bachelor of Science in Criminology'), ('BSEE', 'Bachelor of Science in Electrical Engineering'), ('BSECE', 'Bachelor of Science in Electronics and Communications Engineering'), ('BSES', 'Bachelor of Science in Environmental Science'), ('BSIT', 'Bachelor of Science in Industrial Technology'), ('BSIS', 'Bachelor of Science in Information Systems'), ('BSI/T', 'Bachelor of Science in Information Technology'), ('BSME', 'Bachelor of Science in Mechanical Engineering'), ('BSM', 'Bachelor of Science in Midwifery'), ('BSN', 'Bachelor of Science in Nursing'), ('BSSW ', 'Bachelor of Science in Social Work'), ('BSEd', 'Bachelor of Secondary Education'), ('BTLEd', 'Bachelor of Technology and Livelihood Education')], max_length=10),
        ),
    ]
