# Generated by Django 5.2.7 on 2025-10-30 06:02

import bhms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0003_alter_boarder_degree_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarder',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=bhms.utils.path_and_rename),
        ),
    ]
