# Generated by Django 5.2.7 on 2025-11-27 05:58

import bhms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0004_boarder_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarder',
            name='role',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('STUDENT', 'Student')], default='STUDENT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='boarder',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=bhms.utils.path_and_rename),
        ),
        migrations.AlterField(
            model_name='boarder',
            name='room_number',
            field=models.CharField(choices=[('1F', '1st floor'), ('2FR1', '2nd floor, Room 1'), ('2FR2', '2nd floor, Room 2'), ('2FR3', '2nd floor, Room 3'), ('3FR1', '3rd floor, Room 1'), ('3FR2', '3rd floor, Room 2'), ('3FR3', '3rd floor, Room 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='boarder',
            name='year_level',
            field=models.CharField(choices=[('G11', 'Grade 11'), ('G12', 'Grade 12'), ('FIRST', '1st Year'), ('SECOND', '2nd Year'), ('THIRD', '3rd Year'), ('FOURTH', '4th Year')], max_length=10),
        ),
    ]
