# Generated by Django 5.2.7 on 2025-11-27 06:10

import bhms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0005_boarder_role_alter_boarder_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=bhms.utils.path_and_rename),
        ),
        migrations.AlterField(
            model_name='boarder',
            name='role',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
