# Generated by Django 5.2.7 on 2025-11-27 07:48

import bhms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0006_alter_boarder_profile_photo_alter_boarder_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarder',
            old_name='municipality',
            new_name='city',
        ),
        migrations.AddField(
            model_name='boarder',
            name='region',
            field=models.CharField(blank=True, default='17', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boarder',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=bhms.utils.path_and_rename),
        ),
    ]
