# Generated by Django 5.2.7 on 2025-11-27 16:22

import bhms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0007_rename_municipality_boarder_city_boarder_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=bhms.utils.path_and_rename),
        ),
        migrations.AlterField(
            model_name='boarder',
            name='role',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('STUDENT', 'Student')], default='STUDENT', max_length=20, null=True),
        ),
    ]
