# Generated by Django 5.2.7 on 2026-01-12 08:31

import bhms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarder', '0009_alter_boarder_degree_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarder',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=bhms.utils.path_and_rename),
        ),
        migrations.AlterField(
            model_name='boarder',
            name='role',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('STUDENT', 'Student')], max_length=20, null=True),
        ),
    ]
