# Generated by Django 5.2.7 on 2025-10-24 07:32

import bhms.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boarder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=7, unique=True)),
                ('request_type', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('MAINTENANCE', 'Maintenance Request'), ('SUPPLIES', 'Request for Supplies'), ('CLARIFICATION', 'Clarification'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=bhms.utils.path_and_rename)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='boarder.boarder')),
            ],
        ),
    ]
