# Generated by Django 5.2.7 on 2025-10-21 06:51

import bhms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='reference_number',
            field=models.CharField(editable=False, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=bhms.utils.path_and_rename),
        ),
    ]
