# Generated by Django 5.2.7 on 2025-10-21 06:55

import bhms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0002_servicerequest_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=bhms.utils.path_and_rename),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='reference_number',
            field=models.CharField(default='', editable=False, max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
